### ISSUE TITLE
Enable storing last filter state in local storage

### ISSUE THREAD

**Issue by sharvaibhav** [Aize-Public/finder-react#4]
### Abstract:
The Finder currently resets the filter when we re-load, this makes the user loose the currently selected filters. We want to enable to store the last updated search state in the local storage

### Tasks:

- [ ] Create a model to store the serach state
- [ ] Create a functionality to store the search state model in localstorage.
- [ ] Create functionality to do it on every filter change actions.
- [ ] Add functionality to update the filters on boostrapping time with last used filter state

As we can see currently the filters dont have a way to show unavailble filters, we can create a section in the drop down saying "Unavailabel filters" and then the options how there can be disabled and just informative in nature.
